(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var aa=this||self,l=function(a,b){a=a.split(".");var c=aa;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c=c[d]&&c[d]!==Object.prototype[d]?c[d]:c[d]={}:c[d]=b};var m=function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])},q=function(a){for(var b in a)if(a.hasOwnProperty(b))return!0;return!1};var r=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i;/*

 SPDX-License-Identifier: Apache-2.0
*/
var t=window,u=window.history,v=document,w=navigator,x=function(a,b){v.addEventListener?v.addEventListener(a,b,!1):v.attachEvent&&v.attachEvent("on"+a,b)};var y={},z=function(){y.TAGGING=y.TAGGING||[];y.TAGGING[1]=!0};var A=/:[0-9]+$/,B=function(a,b,c){a=a.split("&");for(var d=0;d<a.length;d++){var e=a[d].split("=");if(decodeURIComponent(e[0]).replace(/\+/g," ")===b)return b=e.slice(1).join("="),c?b:decodeURIComponent(b).replace(/\+/g," ")}},E=function(a,b){b&&(b=String(b).toLowerCase());if("protocol"===b||"port"===b)a.protocol=C(a.protocol)||C(t.location.protocol);"port"===b?a.port=String(Number(a.hostname?a.port:t.location.port)||("http"==a.protocol?80:"https"==a.protocol?443:"")):"host"===b&&(a.hostname=(a.hostname||
t.location.hostname).replace(A,"").toLowerCase());return D(a,b,void 0,void 0,void 0)},D=function(a,b,c,d,e){var f=C(a.protocol);b&&(b=String(b).toLowerCase());switch(b){case "url_no_fragment":d="";a&&a.href&&(d=a.href.indexOf("#"),d=0>d?a.href:a.href.substr(0,d));a=d;break;case "protocol":a=f;break;case "host":a=a.hostname.replace(A,"").toLowerCase();c&&(d=/^www\d*\./.exec(a))&&d[0]&&(a=a.substr(d[0].length));break;case "port":a=String(Number(a.port)||("http"==f?80:"https"==f?443:""));break;case "path":a.pathname||
a.hostname||z();a="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;a=a.split("/");0<=(d||[]).indexOf(a[a.length-1])&&(a[a.length-1]="");a=a.join("/");break;case "query":a=a.search.replace("?","");e&&(a=B(a,e,void 0));break;case "extension":a=a.pathname.split(".");a=1<a.length?a[a.length-1]:"";a=a.split("/")[0];break;case "fragment":a=a.hash.replace("#","");break;default:a=a&&a.href}return a},C=function(a){return a?a.replace(":","").toLowerCase():""},F=function(a){var b=v.createElement("a");a&&
(b.href=a);var c=b.pathname;"/"!==c[0]&&(a||z(),c="/"+c);a=b.hostname.replace(A,"");return{href:b.href,protocol:b.protocol,host:b.host,hostname:a,pathname:c,search:b.search,hash:b.hash,port:b.port}};function G(){for(var a=H,b={},c=0;c<a.length;++c)b[a[c]]=c;return b}function I(){var a="ABCDEFGHIJKLMNOPQRSTUVWXYZ";a+=a.toLowerCase()+"0123456789-_";return a+"."}var H,J;function K(a){H=H||I();J=J||G();for(var b=[],c=0;c<a.length;c+=3){var d=c+1<a.length,e=c+2<a.length,f=a.charCodeAt(c),g=d?a.charCodeAt(c+1):0,h=e?a.charCodeAt(c+2):0,k=f>>2;f=(f&3)<<4|g>>4;g=(g&15)<<2|h>>6;h&=63;e||(h=64,d||(g=64));b.push(H[k],H[f],H[g],H[h])}return b.join("")}
function ba(a){function b(k){for(;d<a.length;){var n=a.charAt(d++),p=J[n];if(null!=p)return p;if(!/^[\s\xa0]*$/.test(n))throw Error("Unknown base64 encoding at char: "+n);}return k}H=H||I();J=J||G();for(var c="",d=0;;){var e=b(-1),f=b(0),g=b(64),h=b(64);if(64===h&&-1===e)return c;c+=String.fromCharCode(e<<2|f>>4);64!=g&&(c+=String.fromCharCode(f<<4&240|g>>2),64!=h&&(c+=String.fromCharCode(g<<6&192|h)))}};var L;var M=void 0,O=function(){var a=ca,b=da,c=N(),d=function(g){a(g.target||g.srcElement||{})},e=function(g){b(g.target||g.srcElement||{})};if(!c.init){x("mousedown",d);x("keyup",d);x("submit",e);var f=HTMLFormElement.prototype.submit;HTMLFormElement.prototype.submit=function(){b(this);f.call(this)};c.init=!0}},P=function(a,b,c,d,e){a={callback:a,domains:b,fragment:2===c,placement:c,forms:d,sameHost:e};N().decorators.push(a)},Q=function(a,b,c){for(var d=N().decorators,e={},f=0;f<d.length;++f){var g=d[f],
h;if(h=!c||g.forms)a:{h=g.domains;var k=a,n=!!g.sameHost;if(h&&(n||k!==v.location.hostname))for(var p=0;p<h.length;p++)if(h[p]instanceof RegExp){if(h[p].test(k)){h=!0;break a}}else if(0<=k.indexOf(h[p])||n&&0<=h[p].indexOf(k)){h=!0;break a}h=!1}h&&(h=g.placement,void 0==h&&(h=g.fragment?2:1),h===b&&m(e,g.callback()))}return e};function N(){var a={};var b=t.google_tag_data;t.google_tag_data=void 0===b?a:b;a=t.google_tag_data;b=a.gl;b&&b.decorators||(b={decorators:[]},a.gl=b);return b};var ea=/(.*?)\*(.*?)\*(.*)/,fa=/([^?#]+)(\?[^#]*)?(#.*)?/;function R(a){return new RegExp("(.*?)(^|&)"+a+"=([^&]*)&?(.*)")}var T=function(a,b){var c=[],d;for(d in a)if(a.hasOwnProperty(d)){var e=a[d];void 0!==e&&e===e&&null!==e&&"[object Object]"!==e.toString()&&(c.push(d),c.push(K(String(e))))}a=c.join("*");void 0!==b&&(c="xp_"+b,b=ha[b](a),a=a+"*"+[c,K(String(b))].join("*"));return["1",S(a),a].join("*")};
function S(a,b){a=[t.navigator.userAgent,(new Date).getTimezoneOffset(),w.userLanguage||w.language,Math.floor((new Date(Date.now())).getTime()/60/1E3)-(void 0===b?0:b),a].join("*");if(!(b=L)){b=Array(256);for(var c=0;256>c;c++){for(var d=c,e=0;8>e;e++)d=d&1?d>>>1^3988292384:d>>>1;b[c]=d}}L=b;b=4294967295;for(c=0;c<a.length;c++)b=b>>>8^L[(b^a.charCodeAt(c))&255];return((b^-1)>>>0).toString(36)}var U={},ha=(U[1]=ia,U[2]=ja,U[3]=ka,U);function ia(){return"CHECKSUM_EXP_DISABLED"}
function ja(){return"CHECKSUM_EXP_DISABLED"}function la(){w.userAgentData&&w.userAgentData.getHighEntropyValues(["architecture","model","bitness","platformVersion","uaFullVersion"]).then(function(){})}function ka(){return"CHECKSUM_EXP_DISABLED"}function ma(a){return function(b){var c=F(t.location.href),d=c.search.replace("?","");var e=B(d,"_gl",!0);b.query=V(e||"")||{};e=E(c,"fragment");var f=e.match(R("_gl"));b.fragment=V(f&&f[3]||"")||{};a&&na(c,d,e)}}
function W(a,b){if(a=R(a).exec(b)){var c=a[2],d=a[4];b=a[1];d&&(b=b+c+d)}return b}function na(a,b,c){function d(f,g){f=W("_gl",f);f.length&&(f=g+f);return f}if(u&&u.replaceState){var e=R("_gl");if(e.test(b)||e.test(c))a=E(a,"path"),b=d(b,"?"),c=d(c,"#"),u.replaceState({},void 0,""+a+b+c)}}
var V=function(a){var b=void 0===b?3:b;try{if(a){a:{for(var c=0;3>c;++c){var d=ea.exec(a);if(d){var e=d;break a}a=decodeURIComponent(a)}e=void 0}if(e&&"1"===e[1]){var f=e[2],g=e[3];a:{for(e=0;e<b;++e)if(f===S(g,e)){var h=!0;break a}h=!1}if(h){b={};var k=g?g.split("*"):[];for(g=0;g<k.length;g+=2)b[k[g]]=ba(k[g+1]);return b}}}}catch(n){}};
function X(a,b,c,d){function e(k){k=W(a,k);var n=k.charAt(k.length-1);k&&"&"!==n&&(k+="&");return k+h}d=void 0===d?!1:d;var f=fa.exec(c);if(!f)return"";c=f[1];var g=f[2]||"";f=f[3]||"";var h=a+"="+b;d?f="#"+e(f.substring(1)):g="?"+e(g.substring(1));return""+c+g+f}function Y(a,b){var c="FORM"===(a.tagName||"").toUpperCase(),d=Q(b,1,c),e=Q(b,2,c);b=Q(b,3,c);var f=M;q(d)&&(d=T(d,f),c?oa("_gl",d,a):Z("_gl",d,a,!1));!c&&q(e)&&(c=T(e),Z("_gl",c,a,!0));for(var g in b)b.hasOwnProperty(g)&&pa(g,b[g],a)}
function pa(a,b,c,d){if(c.tagName){if("a"===c.tagName.toLowerCase())return Z(a,b,c,d);if("form"===c.tagName.toLowerCase())return oa(a,b,c)}if("string"==typeof c)return X(a,b,c,d)}function Z(a,b,c,d){c.href&&(a=X(a,b,c.href,void 0===d?!1:d),r.test(a)&&(c.href=a))}
function oa(a,b,c){if(c&&c.action){var d=(c.method||"").toLowerCase();if("get"===d){d=c.childNodes||[];for(var e=!1,f=0;f<d.length;f++){var g=d[f];if(g.name===a){g.setAttribute("value",b);e=!0;break}}e||(d=v.createElement("input"),d.setAttribute("type","hidden"),d.setAttribute("name",a),d.setAttribute("value",b),c.appendChild(d))}else"post"===d&&(a=X(a,b,c.action),r.test(a)&&(c.action=a))}}
function ca(a){try{a:{for(var b=100;a&&0<b;){if(a.href&&a.nodeName.match(/^a(?:rea)?$/i)){var c=a;break a}a=a.parentNode;b--}c=null}if(c){var d=c.protocol;"http:"!==d&&"https:"!==d||Y(c,c.hostname)}}catch(e){}}function da(a){try{if(a.action){var b=E(F(a.action),"host");Y(a,b)}}catch(c){}};l("google_tag_data.glBridge.auto",function(a,b,c,d,e){O();void 0!==e&&(M=e);3===e&&la();P(a,b,"fragment"===c?2:1,!!d,!1)});l("google_tag_data.glBridge.passthrough",function(a,b,c,d){O();void 0!==d&&(M=d);P(a,[D(t.location,"host",!0)],b,!!c,!0)});l("google_tag_data.glBridge.decorate",function(a,b,c){a=T(a);return pa("_gl",a,b,!!c)});l("google_tag_data.glBridge.generate",T);
l("google_tag_data.glBridge.get",function(a,b){var c=ma(!!b);b=N();b.data||(b.data={query:{},fragment:{}},c(b.data));c={};if(b=b.data)m(c,b.query),a&&m(c,b.fragment);return c});})(window);
(function(){function D(a){var b=1,c;if(a)for(b=0,c=a.length-1;0<=c;c--){var d=a.charCodeAt(c);b=(b<<6&268435455)+d+(d<<14);d=b&266338304;b=0!=d?b^d>>21:b}return b};/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var f=function(a){this.Z=a||[]};f.prototype.set=function(a){this.Z[a]=!0};f.prototype.encode=function(){for(var a=[],b=0;b<this.Z.length;b++)this.Z[b]&&(a[Math.floor(b/6)]^=1<<b%6);for(b=0;b<a.length;b++)a[b]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_".charAt(a[b]||0);return a.join("")+"~"};var fa=window.GoogleAnalyticsObject,ha;if(ha=void 0!=fa)ha=-1<(fa.constructor+"").indexOf("String");var lc;if(lc=ha){var mc=window.GoogleAnalyticsObject;lc=mc?mc.replace(/^[\s\xa0]+|[\s\xa0]+$/g,""):""}var bb=lc||"ga",xd=/^(?:utma\.)?\d+\.\d+$/,zd=/^amp-[\w.-]{22,64}$/,A=!1;var aa=new f;function k(a){aa.set(a)}var da=function(a){a=a.get(ba);ca(a)||(a=[]);a=new f(a);for(var b=aa.Z.slice(),c=0;c<a.Z.length;c++)b[c]=b[c]||a.Z[c];return(new f(b)).encode()};var l=function(a){return"function"==typeof a},ca=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},m=function(a){return void 0!=a&&-1<(a.constructor+"").indexOf("String")},n=function(a,b){return 0==a.indexOf(b)},ea=function(a){return a?a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,""):""},r=function(a){var b=p.createElement("img");b.width=1;b.height=1;b.src=a;return b},t=function(){},u=function(a){if(encodeURIComponent instanceof Function)return encodeURIComponent(a);k(28);return a},
v=function(a,b,c,d){try{a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)}catch(e){k(27)}},cb=/^[\w\-:/.?=&%!\[\]]+$/,pa=/^[\w+/_-]+[=]{0,2}$/,ye=null,pc=function(a,b,c,d,e){if(!ye){ye={createScriptURL:function(h){return h},createHTML:function(h){return h}};try{ye=window.trustedTypes.createPolicy("google-analytics",ye)}catch(h){}}if(a){var g=p.querySelector&&p.querySelector("script[nonce]")||null;g=g?g.nonce||g.getAttribute&&g.getAttribute("nonce")||"":"";c?(e=
d="",b&&cb.test(b)&&(d=' id="'+b+'"'),g&&pa.test(g)&&(e=' nonce="'+g+'"'),cb.test(a)&&p.write(ye.createHTML("<script"+d+e+' src="'+a+'">\x3c/script>'))):(c=p.createElement("script"),c.type="text/javascript",c.async=!0,c.src=ye.createScriptURL(a),d&&(c.onload=d),e&&(c.onerror=e),b&&(c.id=b),g&&c.setAttribute("nonce",g),a=p.getElementsByTagName("script")[0],a.parentNode.insertBefore(c,a))}},sd=function(a,b){return ja(p.location[b?"href":"search"],a)},ja=function(a,b){return(a=a.match("(?:&|#|\\?)"+
u(b).replace(/([.*+?^=!:${}()|\[\]\/\\])/g,"\\$1")+"=([^&#]*)"))&&2==a.length?a[1]:""},td=function(){var a=""+p.location.hostname;return 0==a.indexOf("www.")?a.substring(4):a},nd=function(a,b){var c=a.indexOf(b);if(5==c||6==c)if(a=a.charAt(c+b.length),"/"==a||"?"==a||""==a||":"==a)return!0;return!1},ia=function(a,b){if(1==b.length&&null!=b[0]&&"object"===typeof b[0])return b[0];for(var c={},d=Math.min(a.length+1,b.length),e=0;e<d;e++)if("object"===typeof b[e]){for(var g in b[e])b[e].hasOwnProperty(g)&&
(c[g]=b[e][g]);break}else e<a.length&&(c[a[e]]=b[e]);return c},ge=function(a,b){for(var c=0;c<a.length;c++)if(b==a[c])return!0;return!1};var x=function(){this.pa=[];this.la={};this.v={}};x.prototype.set=function(a,b,c){this.pa.push(a);c?this.v[":"+a]=b:this.la[":"+a]=b};x.prototype.get=function(a){return this.v.hasOwnProperty(":"+a)?this.v[":"+a]:this.la[":"+a]};x.prototype.map=function(a){for(var b=0;b<this.pa.length;b++){var c=this.pa[b],d=this.get(c);d&&a(c,d)}};var z=window,p=document,Be=document.currentScript?document.currentScript.src:"";var id=window,jd=document,wd=function(a){var b=id._gaUserPrefs;if(b&&b.ioo&&b.ioo()||a&&!0===id["ga-disable-"+a])return!0;try{var c=id.external;if(c&&c._gaUserPrefs&&"oo"==c._gaUserPrefs)return!0}catch(g){}a=[];b=String(jd.cookie).split(";");for(c=0;c<b.length;c++){var d=b[c].split("="),e=d[0].replace(/^\s*|\s*$/g,"");e&&"AMP_TOKEN"==e&&((d=d.slice(1).join("=").replace(/^\s*|\s*$/g,""))&&(d=decodeURIComponent(d)),a.push(d))}for(b=0;b<a.length;b++)if("$OPT_OUT"==a[b])return!0;return jd.getElementById("__gaOptOutExtension")?
!0:!1};var ka=function(a){var b=[],c=p.cookie.split(";");a=new RegExp("^\\s*"+a+"=\\s*(.*?)\\s*$");for(var d=0;d<c.length;d++){var e=c[d].match(a);e&&b.push(e[1])}return b},na=function(a,b,c,d,e,g,h){e=wd(e)?!1:la.test(p.location.hostname)||"/"==c&&ma.test(d)?!1:!0;if(!e)return!1;b&&1200<b.length&&(b=b.substring(0,1200));c=a+"="+b+"; path="+c+"; ";g&&(c+="expires="+(new Date((new Date).getTime()+g)).toGMTString()+"; ");d&&"none"!==d&&(c+="domain="+d+";");h&&(c+=h+";");d=p.cookie;p.cookie=c;if(!(d=d!=p.cookie))a:{a=
ka(a);for(d=0;d<a.length;d++)if(b==a[d]){d=!0;break a}d=!1}return d},Cd=function(a){return encodeURIComponent?encodeURIComponent(a).replace(/\(/g,"%28").replace(/\)/g,"%29"):a},ma=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,la=/(^|\.)doubleclick\.net$/i;var he=function(a){var b=[],c=p.cookie.split(";");a=new RegExp("^\\s*"+(a||"_gac")+"_(UA-\\d+-\\d+)=\\s*(.+?)\\s*$");for(var d=0;d<c.length;d++){var e=c[d].match(a);e&&b.push({ga:e[1],value:e[2],timestamp:Number(e[2].split(".")[1])||0})}b.sort(function(g,h){return h.timestamp-g.timestamp});return b};
function we(a,b,c){b=he(b);var d={};if(!b||!b.length)return d;for(var e=0;e<b.length;e++){var g=b[e].value.split(".");if("1"!==g[0]||c&&3>g.length||!c&&3!==g.length)a&&(a.ka=!0);else if(Number(g[1])){d[b[e].ga]?a&&(a.oa=!0):d[b[e].ga]=[];var h={version:g[0],timestamp:1E3*Number(g[1]),ma:g[2]};c&&3<g.length&&(h.labels=g.slice(3));d[b[e].ga].push(h)}}return d};var Od=/^https?:\/\/[^/]*cdn\.ampproject\.org\//,Qd=/^(?:www\.|m\.|amp\.)+/;var Oc=function(a){return(a?"https:":A||"https:"==p.location.protocol?"https:":"http:")+"//www.google-analytics.com"},Wd=function(a){switch(a){default:case 1:return"https://www.google-analytics.com/gtm/js?id=";case 2:return"https://www.googletagmanager.com/gtag/js?id="}},qa=function(a){this.name="len";this.message=a+"-8192"},va=function(a,b,c){c=c||t;if(2036>=b.length)ra(a,b,c);else if(8192>=b.length)sa(a,b,c)||ta(a,b,c)||ra(a,b,c);else throw ua("len",b.length),new qa(b.length);},ra=function(a,b,
c){var d=r(a+"?"+b);d.onload=d.onerror=function(){d.onload=null;d.onerror=null;c()}},ta=function(a,b,c,d){var e=z.XMLHttpRequest;if(!e)return!1;var g=new e;if(!("withCredentials"in g))return!1;a=a.replace(/^http:/,"https:");g.open("POST",a,!0);g.withCredentials=!0;g.setRequestHeader("Content-Type","text/plain");g.onreadystatechange=function(){if(4==g.readyState){if(d&&"text/plain"===g.getResponseHeader("Content-Type"))try{Ud(d,g.responseText,c)}catch(h){ua("xhr","rsp"),c()}else c();g=null}};g.send(b);
return!0},Ud=function(a,b,c){if(1>b.length)ua("xhr","ver","0"),c();else if(3<a.count++)ua("xhr","tmr",""+a.count),c();else{var d=b.charAt(0);if("1"===d)Yd(a,b.substring(1),c);else if(a.J&&"2"===d){var e=b.substring(1).split(","),g=0;b=function(){++g===e.length&&c()};for(d=0;d<e.length;d++)Yd(a,e[d],b)}else ua("xhr","ver",String(b.length)),c()}},Yd=function(a,b,c){if(0===b.length)c();else{var d=b.charAt(0);switch(d){case "d":b=c||t;ta("https://stats.g.doubleclick.net/j/collect?"+a.sa,"",b,a);break;
case "g":ra("https://www.google.com/ads/ga-audiences",a.google,c);(b=b.substring(1))&&(/^[a-z.]{1,6}$/.test(b)?ra("https://www.google.%/ads/ga-audiences".replace("%",b),a.google,t):ua("tld","bcc",b));break;case "G":if(a.J){a.J("G-"+b.substring(1));c();break}case "x":if(a.J){a.J();c();break}default:ua("xhr","brc",d),c()}}},sa=function(a,b,c){return z.navigator.sendBeacon?z.navigator.sendBeacon(a,b)?(c(),!0):!1:!1},ua=function(a,b,c){1<=100*Math.random()||wd("?")||(a=["t=error","_e="+a,"_v=j96","sr=1"],
b&&a.push("_f="+b),c&&a.push("_m="+u(c.substring(0,100))),a.push("aip=1"),a.push("z="+B()),ra(Oc(!0)+"/u/d",a.join("&"),t))};var w=function(){return z.gaData=z.gaData||{}},tb=function(a){var b=w();return b[a]=b[a]||{}};var wa=function(){this.B=[]};wa.prototype.add=function(a){this.B.push(a)};wa.prototype.o=function(a){try{for(var b=0;b<this.B.length;b++){var c=a.get(this.B[b]);c&&l(c)&&c.call(z,a)}}catch(d){}b=a.get(C);b!=t&&l(b)&&(a.set(C,t,!0),setTimeout(b,10))};function xa(a){if(100!=a.get(ya)&&D(E(a,F))%1E4>=100*G(a,ya))throw"abort";}function za(a){if(wd(E(a,H)))throw"abort";}function Aa(){var a=p.location.protocol;if("http:"!=a&&"https:"!=a)throw"abort";}
function Ba(a){try{z.navigator.sendBeacon?k(42):z.XMLHttpRequest&&"withCredentials"in new z.XMLHttpRequest&&k(40)}catch(c){}a.set(Ca,da(a),!0);a.set(Da,G(a,Da)+1);var b=[];I.map(function(c,d){d.da&&(c=a.get(c),void 0!=c&&c!=d.defaultValue&&("boolean"==typeof c&&(c*=1),b.push(d.da+"="+u(""+c))))});!1===a.get(Kd)&&b.push("npa=1");b.push("z="+J());a.set(Ea,b.join("&"),!0)}
function Fa(a){var b=E(a,Ha);!b&&a.get(Ia)&&(b="beacon");var c=E(a,Ga),d=E(a,Pc),e=c||(d||Oc(!1)+"/internal")+"/collect";switch(E(a,Va)){case "d":e=c||(d||Oc(!1)+"/internal")+"/j/collect";b=a.get(Ld)||void 0;c=E(a,Ea);d=(d=a.D(C))||t;ta(e+"?"+c,"",d,b);break;default:b?(c=E(a,Ea),d=(d=a.D(C))||t,"image"==b?ra(e,c,d):"xhr"==b&&ta(e,c,d)||"beacon"==b&&sa(e,c,d)||va(e,c,d)):va(e,E(a,Ea),a.D(C))}e=E(a,H);e=tb(e);b=e.hitcount;e.hitcount=b?b+1:1;e.first_hit||(e.first_hit=(new Date).getTime());e=E(a,H);delete tb(e).pending_experiments;
a.set(C,t,!0)}function Ja(a){w().expId&&a.set(Ka,w().expId);w().expVar&&a.set(La,w().expVar);var b=E(a,H);if(b=tb(b).pending_experiments){var c=[];for(d in b)b.hasOwnProperty(d)&&b[d]&&c.push(encodeURIComponent(d)+"."+encodeURIComponent(b[d]));var d=c.join("!")}else d=void 0;d&&((b=a.get(ub))&&(d=b+"!"+d),a.set(ub,d,!0))}function Ma(){if(z.navigator&&"preview"==z.navigator.loadPurpose)throw"abort";}
function Na(a){var b=z.gaDevIds||[];if(ca(b)){var c=a.get("&did");m(c)&&0<c.length&&(b=b.concat(c.split(",")));c=[];for(var d=0;d<b.length;d++)ge(c,b[d])||c.push(b[d]);0!=c.length&&a.set("&did",c.join(","),!0)}}function Oa(a){if(!a.get(H))throw"abort";}
function pe(a){try{if(!a.get(qe)&&(a.set(qe,!0),!a.get("&gtm"))){var b=void 0;De(sd("gtm_debug"))&&(b=2);!b&&n(p.referrer,"https://tagassistant.google.com/")&&(b=3);!b&&ge(p.cookie.split("; "),"__TAG_ASSISTANT=x")&&(b=4);if(!b){var c=p.documentElement.getAttribute("data-tag-assistant-present");De(c)&&(b=5)}if(b){z["google.tagmanager.debugui2.queue"]||(z["google.tagmanager.debugui2.queue"]=[],pc("https://www.google-analytics.com/debug/bootstrap?id="+a.get(H)+"&src=LEGACY&cond="+b));var d=p.currentScript;
z["google.tagmanager.debugui2.queue"].push({messageType:"LEGACY_CONTAINER_STARTING",data:{id:a.get(H),scriptSource:d&&d.src||""}})}}}catch(e){}}function De(a){if(null==a||0===a.length)return!1;a=Number(a);var b=Date.now();return a<b+3E5&&a>b-9E5};var B=function(){return Math.round(2147483647*Math.random())},J=function(){try{var a=new Uint32Array(1);z.crypto.getRandomValues(a);return a[0]&2147483647}catch(b){return B()}};function Pa(a){var b=G(a,Qa);500<=b&&k(15);var c=E(a,Ra);if("transaction"!=c&&"item"!=c){c=G(a,Sa);var d=(new Date).getTime(),e=G(a,Ta);0==e&&a.set(Ta,d);e=Math.round(2*(d-e)/1E3);0<e&&(c=Math.min(c+e,20),a.set(Ta,d));if(0>=c)throw"abort";a.set(Sa,--c)}a.set(Qa,++b)};var Ua=function(){this.data=new x};Ua.prototype.get=function(a){var b=Wa(a),c=this.data.get(a);b&&void 0==c&&(c=l(b.defaultValue)?b.defaultValue():b.defaultValue);return b&&b.D?b.D(this,a,c):c};var E=function(a,b){a=a.get(b);return void 0==a?"":""+a},G=function(a,b){a=a.get(b);return void 0==a||""===a?0:Number(a)};Ua.prototype.D=function(a){return(a=this.get(a))&&l(a)?a:t};
Ua.prototype.set=function(a,b,c){if(a)if("object"==typeof a)for(var d in a)a.hasOwnProperty(d)&&Xa(this,d,a[d],c);else Xa(this,a,b,c)};var Xa=function(a,b,c,d){if(void 0!=c)switch(b){case H:Ya.test(c)}var e=Wa(b);e&&e.I?e.I(a,b,c,d):a.data.set(b,c,d)};var I=new x,ld=[],K=function(a,b,c,d,e){this.name=a;this.da=b;this.D=d;this.I=e;this.defaultValue=c},Wa=function(a){var b=I.get(a);if(!b)for(var c=0;c<ld.length;c++){var d=ld[c],e=d[0].exec(a);if(e){b=d[1](e);I.set(b.name,b);break}}return b},Za=function(a){var b;I.map(function(c,d){d.da==a&&(b=d)});return b&&b.name},L=function(a,b,c,d,e){a=new K(a,b,c,d,e);I.set(a.name,a);return a.name},$a=function(a,b){ld.push([new RegExp("^"+a+"$"),b])},M=function(a,b,c){return L(a,b,c,void 0,ab)},ab=function(){};var db=M("apiVersion","v"),eb=M("clientVersion","_v");L("anonymizeIp","aip");var fb=L("adSenseId","a"),Ra=L("hitType","t"),C=L("hitCallback"),Ea=L("hitPayload");L("nonInteraction","ni");L("currencyCode","cu");L("dataSource","ds");var Ia=L("useBeacon",void 0,!1),Ha=L("transport");L("sessionControl","sc","");L("sessionGroup","sg");L("queueTime","qt");var Da=L("_s","_s");L("screenName","cd");var gb=L("location","dl",""),hb=L("referrer","dr"),ib=L("page","dp","");L("hostname","dh");
var jb=L("language","ul"),kb=L("encoding","de");L("title","dt",function(){return p.title||void 0});$a("contentGroup([0-9]+)",function(a){return new K(a[0],"cg"+a[1])});var lb=L("screenColors","sd"),mb=L("screenResolution","sr"),nb=L("viewportSize","vp"),ob=L("javaEnabled","je"),pb=L("flashVersion","fl");L("campaignId","ci");L("campaignName","cn");L("campaignSource","cs");L("campaignMedium","cm");L("campaignKeyword","ck");L("campaignContent","cc");
var qb=L("eventCategory","ec"),rb=L("eventAction","ea"),sb=L("eventLabel","el"),vb=L("eventValue","ev"),wb=L("socialNetwork","sn"),xb=L("socialAction","sa"),yb=L("socialTarget","st"),zb=L("l1","plt"),Ab=L("l2","pdt"),Bb=L("l3","dns"),Cb=L("l4","rrt"),Db=L("l5","srt"),Eb=L("l6","tcp"),Fb=L("l7","dit"),Gb=L("l8","clt"),ie=L("l9","_gst"),je=L("l10","_gbt"),ke=L("l11","_cst"),le=L("l12","_cbt"),Hb=L("timingCategory","utc"),Ib=L("timingVar","utv"),Jb=L("timingLabel","utl"),Kb=L("timingValue","utt");
L("appName","an");L("appVersion","av","");L("appId","aid","");L("appInstallerId","aiid","");L("exDescription","exd");L("exFatal","exf");var Ka=L("expId","xid"),La=L("expVar","xvar"),ub=L("exp","exp"),Lb=L("_utma","_utma"),Mb=L("_utmz","_utmz"),Nb=L("_utmht","_utmht"),Qa=L("_hc",void 0,0),Ta=L("_ti",void 0,0),Sa=L("_to",void 0,20);$a("dimension([0-9]+)",function(a){return new K(a[0],"cd"+a[1])});$a("metric([0-9]+)",function(a){return new K(a[0],"cm"+a[1])});L("linkerParam",void 0,void 0,Ob,ab);
var me=M("_cd2l",void 0,!1),Ca=L("usage","_u"),ba=L("_um");L("forceSSL",void 0,void 0,function(){return A},function(a,b,c){k(34);A=!!c});L("_j1","jid");L("_j2","gjid");$a("\\&(.*)",function(a){var b=new K(a[0],a[1]),c=Za(a[0].substring(1));c&&(b.D=function(d){return d.get(c)},b.I=function(d,e,g,h){d.set(c,g,h)},b.da=void 0);return b});
var Pb=M("_oot"),Qb=L("previewTask"),Rb=L("checkProtocolTask"),Sb=L("validationTask"),Tb=L("checkStorageTask"),Ub=L("historyImportTask"),Vb=L("samplerTask"),Wb=L("_rlt"),Xb=L("buildHitTask"),Yb=L("sendHitTask"),Zb=L("ceTask"),$b=L("devIdTask"),ac=L("timingTask"),bc=L("displayFeaturesTask"),ud=L("customTask"),Md=L("fpsCrossDomainTask"),re=M("_cta"),N=M("name"),F=M("clientId","cid"),nc=M("clientIdTime"),Ad=M("storedClientId"),cc=L("userId","uid"),H=M("trackingId","tid"),dc=M("cookieName",void 0,"_ga"),
O=M("cookieDomain"),P=M("cookiePath",void 0,"/"),ec=M("cookieExpires",void 0,63072E3),Bd=M("cookieUpdate",void 0,!0),Td=M("cookieFlags",void 0,""),fc=M("legacyCookieDomain"),gc=M("legacyHistoryImport",void 0,!0),Q=M("storage",void 0,"cookie"),hc=M("allowLinker",void 0,!1),ic=M("allowAnchor",void 0,!0),ya=M("sampleRate","sf",100),jc=M("siteSpeedSampleRate",void 0,1),kc=M("alwaysSendReferrer",void 0,!1),od=M("_gid","_gid"),rd=M("_gcn"),qd=M("useAmpClientId"),Dd=M("_gclid"),Ed=M("_gt"),Fd=M("_ge",void 0,
7776E6),Gd=M("_gclsrc"),Hd=M("storeGac",void 0,!0),Pc=L("_x_19"),Sd=L("_fplc","_fplc"),ae=M("_cs"),be=M("_useUp",void 0,!1),ee=L("up","up"),qe=L("_tac",void 0,!1),se=M("_gbraid"),te=M("_gbt"),ue=M("_gbe",void 0,7776E6),Ga=L("transportUrl");L("_r","_r");L("_slc","_slc");var Ld=L("_dp"),Va=L("_jt",void 0,"n"),$d=L("allowAdFeatures",void 0,!0),Kd=L("allowAdPersonalizationSignals",void 0,!0);
function R(a,b,c,d){b[a]=function(){try{return d&&k(d),c.apply(this,arguments)}catch(e){throw ua("exc",a,e&&e.name),e;}}};var Zd=function(a){if("cookie"==a.get(Q))return a=ka("FPLC"),0<a.length?a[0]:void 0},Vd=function(a){var b;if(b=E(a,Pc)&&a.get(me))b=Rd.get(a.get(ic)),b=!(b&&b._fplc);b&&!Zd(a)&&a.set(Sd,"0")};var kd=function(a){var b=Math.min(G(a,jc),100);return D(E(a,F))%100>=b?!1:!0},sc=function(a){var b={};if(qc(b)||rc(b)){var c=b[zb];void 0==c||Infinity==c||isNaN(c)||(0<c?(S(b,Bb),S(b,Eb),S(b,Db),S(b,Ab),S(b,Cb),S(b,Fb),S(b,Gb),S(b,ie),S(b,je),S(b,ke),S(b,le),setTimeout(function(){a(b)},10)):v(z,"load",function(){sc(a)},!1))}},qc=function(a){var b=z.performance||z.webkitPerformance;b=b&&b.timing;if(!b)return!1;var c=b.navigationStart;if(0==c)return!1;a[zb]=b.loadEventStart-c;a[Bb]=b.domainLookupEnd-
b.domainLookupStart;a[Eb]=b.connectEnd-b.connectStart;a[Db]=b.responseStart-b.requestStart;a[Ab]=b.responseEnd-b.responseStart;a[Cb]=b.fetchStart-c;a[Fb]=b.domInteractive-c;a[Gb]=b.domContentLoadedEventStart-c;a[ie]=Z.ca-c;a[je]=Z.na-c;z.google_tag_manager&&z.google_tag_manager._li&&(b=z.google_tag_manager._li,a[ke]=b.cst,a[le]=b.cbt);return!0},rc=function(a){if(z.top!=z)return!1;var b=z.external,c=b&&b.onloadT;b&&!b.isValidLoadTime&&(c=void 0);2147483648<c&&(c=void 0);0<c&&b.setPageReadyTime();if(void 0==
c)return!1;a[zb]=c;return!0},S=function(a,b){var c=a[b];if(isNaN(c)||Infinity==c||0>c)a[b]=void 0},tc=function(a){return function(b){if("pageview"==b.get(Ra)&&!a.$){a.$=!0;var c=kd(b),d=0<ja(E(b,gb),"gclid").length,e=0<ja(E(b,gb),"wbraid").length;(c||d||e)&&sc(function(g){c&&a.send("timing",g);(d||e)&&a.send("adtiming",g)})}}};var T=!1,xc=function(a){if("cookie"==E(a,Q)){if(a.get(Bd)||E(a,Ad)!=E(a,F)){var b=1E3*G(a,ec);a:{var c=F,d=uc(a,c);if(d){var e=E(a,dc),g=vc(E(a,P)),h=wc(E(a,O)),q=E(a,Td),y=E(a,H);if("auto"!=h)na(e,d,g,h,y,b,q)&&(T=!0);else{k(32);b:{d=[];h=td().split(".");if(4==h.length){var oa=h[h.length-1];if(parseInt(oa,10)==oa){oa=["none"];break b}}for(oa=h.length-2;0<=oa;oa--)d.push(h.slice(oa).join("."));h=p.location.hostname;la.test(h)||ma.test(h)||d.push("none");oa=d}for(var Nd=0;Nd<oa.length;Nd++)if(h=oa[Nd],
a.data.set(O,h),d=uc(a,c),na(e,d,g,h,y,b,q)){T=!0;break a}a.data.set(O,"auto")}}else k(54)}a.data.set(Ad,E(a,F))}if(a.get(Hd)){if(b=E(a,Dd))c=Math.min(G(a,Fd),1E3*G(a,ec)),c=0===c?0:Math.min(c,1E3*G(a,Ed)+c-(new Date).getTime()),a.data.set(Fd,c),e={},h=E(a,Ed),oa=E(a,Gd),g=vc(E(a,P)),q=wc(E(a,O)),y=E(a,H),d=E(a,Td),oa&&"aw.ds"!=oa?e&&(e.ra=!0):(b=["1",h,Cd(b)].join("."),0<=c&&(e&&(e.qa=!0),na("_gac_"+Cd(y),b,g,q,y,c,d))),Jd(e)}else k(75);a.get(Hd)&&(b=E(a,se))&&(c=Math.min(G(a,ue),1E3*G(a,ec)),c=
0===c?0:Math.min(c,1E3*G(a,te)+c-(new Date).getTime()),a.data.set(ue,c),e={},d=E(a,te),g=vc(E(a,P)),q=wc(E(a,O)),y=E(a,H),a=E(a,Td),b=["1",d,Cd(b)].join("."),0<=c&&(e&&(e.qa=!0),na("_gac_gb_"+Cd(y),b,g,q,y,c,a)),xe(e))}},yc=function(a){if("cookie"==E(a,Q)&&!T&&(xc(a),!T))throw"abort";},Ac=function(a){if(a.get(gc)){var b=E(a,O),c=E(a,fc)||td(),d=zc("__utma",c,b);d&&(k(19),a.set(Nb,(new Date).getTime(),!0),a.set(Lb,d.P),(b=zc("__utmz",c,b))&&d.hash==b.hash&&a.set(Mb,b.P))}},uc=function(a,b){b=Cd(E(a,
b));var c=wc(E(a,O)).split(".").length;a=Cc(E(a,P));1<a&&(c+="-"+a);return b?["GA1",c,b].join("."):""},Dc=function(a,b,c){for(var d=[],e=[],g,h=0;h<a.length;h++){var q=a[h];q.m[c]==b?d.push(q):void 0==g||q.m[c]<g?(e=[q],g=q.m[c]):q.m[c]==g&&e.push(q)}return 0<d.length?d:e},wc=function(a){return 0==a.indexOf(".")?a.substr(1):a},vc=function(a){if(!a)return"/";1<a.length&&a.lastIndexOf("/")==a.length-1&&(a=a.substr(0,a.length-1));0!=a.indexOf("/")&&(a="/"+a);return a},Cc=function(a){a=vc(a);return"/"==
a?1:a.split("/").length},Jd=function(a){a.qa&&k(77);a.ka&&k(74);a.oa&&k(73);a.ra&&k(69)},xe=function(a){a.qa&&k(85);a.ka&&k(86);a.oa&&k(87)};function zc(a,b,c){"none"==b&&(b="");var d=[],e=ka(a);a="__utma"==a?6:2;for(var g=0;g<e.length;g++){var h=(""+e[g]).split(".");h.length>=a&&d.push({hash:h[0],P:e[g],O:h})}if(0!=d.length)return 1==d.length?d[0]:Ec(b,d)||Ec(c,d)||Ec(null,d)||d[0]}function Ec(a,b){if(null==a)var c=a=1;else c=D(a),a=D(n(a,".")?a.substring(1):"."+a);for(var d=0;d<b.length;d++)if(b[d].hash==c||b[d].hash==a)return b[d]};var Gc=new RegExp(/^https?:\/\/([^\/:]+)/),Rd=z.google_tag_data.glBridge,Qc=RegExp("(.*)([?&#])(?:_ga=[^&#]*)(?:&?)(.*)"),Rc=RegExp("(.*)([?&#])(?:_gac=[^&#]*)(?:&?)(.*)");function Ob(a){if(a.get(me))return k(35),Rd.generate(ne(a));var b=E(a,F),c=E(a,od)||"";b="_ga=2."+u(vd(c+b,0)+"."+c+"-"+b);(a=oe(a))?(k(44),a="&_gac=1."+u([vd(a.ma,0),a.timestamp,a.ma].join("."))):a="";return b+a}
function Hc(a,b){var c=new Date,d=z.navigator,e=d.plugins||[];a=[a,d.userAgent,c.getTimezoneOffset(),c.getYear(),c.getDate(),c.getHours(),c.getMinutes()+b];for(b=0;b<e.length;++b)a.push(e[b].description);return D(a.join("."))}function vd(a,b){var c=new Date,d=z.navigator,e=c.getHours()+Math.floor((c.getMinutes()+b)/60);return D([a,d.userAgent,d.language||"",c.getTimezoneOffset(),c.getYear(),c.getDate()+Math.floor(e/24),(24+e)%24,(60+c.getMinutes()+b)%60].join("."))}
var U=function(a){k(48);this.target=a;this.K=!1};U.prototype.S=function(a,b){if(a){if(this.target.get(me))return Rd.decorate(ne(this.target),a,b);if(a.tagName){if("a"==a.tagName.toLowerCase()){a.href&&(a.href=Ic(this,a.href,b));return}if("form"==a.tagName.toLowerCase())return Jc(this,a)}if("string"==typeof a)return Ic(this,a,b)}};
var Ic=function(a,b,c){var d=Qc.exec(b);d&&3<=d.length&&(b=d[1]+(d[3]?d[2]+d[3]:""));(d=Rc.exec(b))&&3<=d.length&&(b=d[1]+(d[3]?d[2]+d[3]:""));a=a.target.get("linkerParam");d=b.indexOf("?");var e=b.indexOf("#");b=c?b+((-1==e?"#":"&")+a):-1==e?b+((-1===d?"?":"&")+a):b.substring(0,e)+(-1===d||d>e?"?":"&")+a+b.substring(e);b=b.replace(/&+_ga=/,"&_ga=");return b=b.replace(RegExp("&+_gac="),"&_gac=")},Jc=function(a,b){if(b&&b.action)if("get"==b.method.toLowerCase()){a=a.target.get("linkerParam").split("&");
for(var c=0;c<a.length;c++){var d=a[c].split("="),e=d[1];d=d[0];for(var g=b.childNodes||[],h=!1,q=0;q<g.length;q++)if(g[q].name==d){g[q].setAttribute("value",e);h=!0;break}h||(g=p.createElement("input"),g.setAttribute("type","hidden"),g.setAttribute("name",d),g.setAttribute("value",e),b.appendChild(g))}}else"post"==b.method.toLowerCase()&&(b.action=Ic(a,b.action))};
U.prototype.R=function(a,b,c){function d(g){try{g=g||z.event;a:{var h=g.target||g.srcElement;for(g=100;h&&0<g;){if(h.href&&h.nodeName.match(/^a(?:rea)?$/i)){var q=h;break a}h=h.parentNode;g--}q={}}("http:"==q.protocol||"https:"==q.protocol)&&Kc(a,q.hostname||"")&&q.href&&(q.href=Ic(e,q.href,b))}catch(y){k(26)}}var e=this;this.target.get(me)?Rd.auto(function(){return ne(e.target)},a,b?"fragment":"",c):(this.K||(this.K=!0,v(p,"mousedown",d,!1),v(p,"keyup",d,!1)),c&&v(p,"submit",function(g){g=g||z.event;
if((g=g.target||g.srcElement)&&g.action){var h=g.action.match(Gc);h&&Kc(a,h[1])&&Jc(e,g)}}))};U.prototype.H=function(a){if(a){var b=this,c=b.target.get(ae);void 0!==c&&Rd.passthrough(function(){if(c("analytics_storage"))return{};var d={};return d._ga=b.target.get(F),d._up="1",d},1,!0)}};function Kc(a,b){if(b==p.location.hostname)return!1;for(var c=0;c<a.length;c++)if(a[c]instanceof RegExp){if(a[c].test(b))return!0}else if(0<=b.indexOf(a[c]))return!0;return!1}
function Id(a,b){return b!=Hc(a,0)&&b!=Hc(a,-1)&&b!=Hc(a,-2)&&b!=vd(a,0)&&b!=vd(a,-1)&&b!=vd(a,-2)}function ne(a){var b=oe(a),c={};c._ga=a.get(F);c._gid=a.get(od)||void 0;c._gac=b?[b.ma,b.timestamp].join("."):void 0;b=a.get(Sd);a=Zd(a);return c._fplc=b&&"0"!==b?b:a,c}function oe(a){function b(e){return void 0==e||""===e?0:Number(e)}var c=a.get(Dd);if(c&&a.get(Hd)){var d=b(a.get(Ed));if(1E3*d+b(a.get(Fd))<=(new Date).getTime())k(76);else return{timestamp:d,ma:c}}};var oc=/^(GTM|OPT)-[A-Z0-9]+$/,ce=/^G-[A-Z0-9]+$/,Bc=/;_gaexp=[^;]*/g,ad=/;((__utma=)|([^;=]+=GAX?\d+\.))[^;]*/g,yd=/^https?:\/\/[\w\-.]+\.google.com(:\d+)?\/optimize\/opt-launch\.html\?.*$/,bd=function(a){function b(d,e){e&&(c+="&"+d+"="+u(e))}var c=Wd(a.type)+u(a.id);"dataLayer"!=a.G&&b("l",a.G);b("cx",a.context);b("t",a.target);b("cid",a.clientId);b("cidt",a.ha);b("gac",a.ia);b("aip",a.fa);a.sync&&b("m","sync");b("cycle",a.ba);a.ma&&b("gclid",a.ma);yd.test(p.referrer)&&b("cb",String(B()));return c},
Xd=function(a,b){var c=(new Date).getTime();z[a.G]=z[a.G]||[];c={"gtm.start":c};a.sync||(c.event="gtm.js");z[a.G].push(c);2===a.type&&function(d,e,g){z[a.G].push(arguments)}("config",a.id,b)},Fc=function(a,b,c,d){c=c||{};var e=1;ce.test(b)&&(e=2);var g={id:b,type:e,G:c.dataLayer||"dataLayer",ba:!1},h=void 0;a.get("&gtm")==b&&(g.ba=!0);1===e?(g.fa=!!a.get("anonymizeIp"),g.sync=d,b=String(a.get("name")),"t0"!=b&&(g.target=b),wd(String(a.get("trackingId")))||(g.clientId=String(a.get(F)),g.ha=Number(a.get(nc)),
c=c.palindrome?ad:Bc,c=(c=p.cookie.replace(/^|(; +)/g,";").match(c))?c.sort().join("").substring(1):void 0,g.ia=c,g.ma=ja(E(a,gb),"gclid"))):2===e&&(g.context="c",h={allow_google_signals:a.get($d),allow_ad_personalization_signals:a.get(Kd)});Xd(g,h);return bd(g)};var Lc=function(){};var Mc=function(){};var Nc=function(){var a=z.gaGlobal=z.gaGlobal||{};return a.hid=a.hid||B()};var Ya=/^(UA|YT|MO|GP)-(\d+)-(\d+)$/,V=function(a){function b(e,g){d.model.data.set(e,g)}function c(e,g){b(e,g);d.filters.add(e)}var d=this;this.model=new Ua;this.filters=new wa;b(N,a[N]);b(H,ea(a[H]));b(dc,a[dc]);b(O,a[O]||td());b(P,a[P]);b(ec,a[ec]);b(Bd,a[Bd]);b(Td,a[Td]);b(fc,a[fc]);b(gc,a[gc]);b(hc,a[hc]);b(ic,a[ic]);b(ya,a[ya]);b(jc,a[jc]);b(kc,a[kc]);b(Q,a[Q]);b(cc,a[cc]);b(nc,a[nc]);b(qd,a[qd]);b(Hd,a[Hd]);b(me,a[me]);b(Pc,a[Pc]);b(be,a[be]);b(ae,a[ae]);b(db,1);b(eb,"j96");c(re,pe);c(Pb,za);
c(ud,t);c(Qb,Ma);c(Rb,Aa);c(Sb,Oa);c(Tb,yc);c(Ub,Ac);c(Vb,xa);c(Wb,Pa);c(Zb,Ja);c($b,Na);c(bc,Mc);c(Md,Vd);c(Xb,Ba);c(Yb,Fa);c(ac,tc(this));Sc(this.model);Uc(this.model,a[F]);this.model.set(fb,Nc())};V.prototype.get=function(a){return this.model.get(a)};V.prototype.set=function(a,b){this.model.set(a,b)};
V.prototype.send=function(a){if(!(1>arguments.length)){if("string"===typeof arguments[0]){var b=arguments[0];var c=[].slice.call(arguments,1)}else b=arguments[0]&&arguments[0][Ra],c=arguments;b&&(c=ia($c[b]||[],c),c[Ra]=b,this.model.set(c,void 0,!0),this.filters.o(this.model),this.model.data.v={})}};V.prototype.ja=function(a,b){var c=this;cd(a,c,b)||(dd(a,function(){cd(a,c,b)}),ed(String(c.get(N)),a,void 0,b,!0))};
var Uc=function(a,b){var c=E(a,dc);a.data.set(rd,"_ga"==c?"_gid":c+"_gid");if("cookie"==E(a,Q)){T=!1;b:{c=ka(E(a,dc));var d=E(a,O),e=E(a,P);if(!c||1>c.length)k(12);else{for(var g=[],h=0;h<c.length;h++){var q=c[h];var y=q.split(".");var oa=y.shift();("GA1"==oa||"1"==oa)&&1<y.length?(q=y.shift().split("-"),1==q.length&&(q[1]="1"),q[0]*=1,q[1]*=1,y={m:q,A:y.join(".")}):y=zd.test(q)?{m:[0,0],A:q}:void 0;y&&g.push(y)}if(1==g.length){k(13);c=g[0].A;break b}if(0==g.length)k(12);else{k(14);g=Dc(g,wc(d).split(".").length,
0);if(1==g.length){c=g[0].A;break b}g=Dc(g,Cc(e),1);1<g.length&&k(41);c=g[0]&&g[0].A;break b}}c=void 0}c||(c=E(a,O),d=E(a,fc)||td(),c=zc("__utma",d,c),void 0!=c?(k(10),c=c.O[1]+"."+c.O[2]):c=void 0);c&&(T=!0);if(d=c&&!a.get(Bd))d=c.split("."),2!=d.length?d=!1:(d=Number(d[1]))?(e=G(a,ec),d=d+e<(new Date).getTime()/1E3):d=!1;d&&(c=void 0);c&&(a.data.set(Ad,c),a.data.set(F,c));a.get(Hd)&&(c=a.get(Dd),d=a.get(Gd),!c||d&&"aw.ds"!=d)&&(c={},d=(p?we(c):{})[E(a,H)],Jd(c),d&&0!=d.length&&(c=d[0],a.data.set(Ed,
c.timestamp/1E3),a.data.set(Dd,c.ma)));a.get(Hd)&&(c=a.get(se),d={},e=(p?we(d,"_gac_gb",!0):{})[E(a,H)],xe(d),e&&0!=e.length&&(d=e[0],e=d.ma,c&&c!==e||(d.labels&&d.labels.length&&(e+="."+d.labels.join(".")),a.data.set(te,d.timestamp/1E3),a.data.set(se,e))))}if(a.get(Bd)){c=sd("_ga",!!a.get(ic));g=sd("_gl",!!a.get(ic));d=Rd.get(a.get(ic));e=d._ga;g&&0<g.indexOf("_ga*")&&!e&&k(30);if(b||!a.get(be))g=!1;else if(g=a.get(ae),void 0===g||g("analytics_storage"))g=!1;else{k(84);a.data.set(ee,1);if(g=d._up)(g=
Gc.exec(p.referrer))?(g=g[1],h=p.location.hostname,g=h===g||0<=h.indexOf("."+g)||0<=g.indexOf("."+h)?!0:!1):g=!1;g=g?!0:!1}h=d.gclid;y=d._gac;if(c||e||h||y){c&&e&&k(36);if(!(q=a.get(hc))){q=a.get(qd);b:{if(Od.test(p.referrer)){oa=p.location.hostname.replace(Qd,"");c:{var Nd=p.referrer;Nd=Nd.replace(/^https?:\/\//,"");var Pd=Nd.replace(/^[^/]+/,"").split("/"),de=Pd[2];Pd=(Pd="s"==de?Pd[3]:de)?decodeURIComponent(Pd):Pd;if(!Pd){if(0==Nd.indexOf("xn--")){Nd="";break c}(Nd=Nd.match(/(.*)\.cdn\.ampproject\.org\/?$/))&&
2==Nd.length&&(Pd=Nd[1].replace(/-/g,".").replace(/\.\./g,"-"))}Nd=Pd?Pd.replace(Qd,""):""}(Pd=oa===Nd)||(Nd="."+Nd,Pd=oa.substring(oa.length-Nd.length,oa.length)===Nd);if(Pd){oa=!0;break b}else k(78)}oa=!1}q=oa&&!1!==q}if(q||g){if(e&&(k(38),a.data.set(F,e),d._gid&&(k(51),a.data.set(od,d._gid))),h?(k(82),a.data.set(Dd,h),d.gclsrc&&a.data.set(Gd,d.gclsrc)):y&&(e=y.split("."))&&2===e.length&&(k(37),a.data.set(Dd,e[0]),a.data.set(Ed,e[1])),(d=d._fplc)&&E(a,Pc)&&(k(83),a.data.set(Sd,d)),c)b:if(d=c.indexOf("."),
-1==d)k(22);else{e=c.substring(0,d);g=c.substring(d+1);d=g.indexOf(".");c=g.substring(0,d);g=g.substring(d+1);if("1"==e){if(d=g,Id(d,c)){k(23);break b}}else if("2"==e){d=g.indexOf("-");e="";0<d?(e=g.substring(0,d),d=g.substring(d+1)):d=g.substring(1);if(Id(e+d,c)){k(53);break b}e&&(k(2),a.data.set(od,e))}else{k(22);break b}k(11);a.data.set(F,d);if(c=sd("_gac",!!a.get(ic)))c=c.split("."),"1"!=c[0]||4!=c.length?k(72):Id(c[3],c[1])?k(71):(a.data.set(Dd,c[3]),a.data.set(Ed,c[2]),k(70))}}else k(21)}}b&&
(k(9),a.data.set(F,u(b)));if(!a.get(F))if(b=(b=z.gaGlobal)&&b.from_cookie&&"cookie"!==E(a,Q)?void 0:(b=b&&b.vid)&&-1!==b.search(xd)?b:void 0,b)k(17),a.data.set(F,b);else{k(8);b=z.navigator.userAgent+(p.cookie?p.cookie:"")+(p.referrer?p.referrer:"");c=b.length;for(d=z.history.length;0<d;)b+=d--^c++;a.data.set(F,[B()^D(b)&2147483647,Math.round((new Date).getTime()/1E3)].join("."))}xc(a);b=z.gaGlobal=z.gaGlobal||{};c=E(a,F);a=c===E(a,Ad);if(void 0==b.vid||a&&!b.from_cookie)b.vid=c,b.from_cookie=a},Sc=
function(a){var b=z.navigator,c=z.screen,d=p.location,e=a.set;a:{var g=!!a.get(kc),h=!!a.get(qd);var q=p.referrer;if(/^(https?|android-app):\/\//i.test(q)){if(g)break a;g="//"+p.location.hostname;if(!nd(q,g)){if(h&&(h=g.replace(/\./g,"-")+".cdn.ampproject.org",nd(q,h))){q=void 0;break a}break a}}q=void 0}e.call(a,hb,q);d&&(e=d.pathname||"","/"!=e.charAt(0)&&(k(31),e="/"+e),a.set(gb,d.protocol+"//"+d.hostname+e+d.search));c&&a.set(mb,c.width+"x"+c.height);c&&a.set(lb,c.colorDepth+"-bit");c=p.documentElement;
q=(e=p.body)&&e.clientWidth&&e.clientHeight;h=[];c&&c.clientWidth&&c.clientHeight&&("CSS1Compat"===p.compatMode||!q)?h=[c.clientWidth,c.clientHeight]:q&&(h=[e.clientWidth,e.clientHeight]);c=0>=h[0]||0>=h[1]?"":h.join("x");a.set(nb,c);c=a.set;var y;if((e=(e=z.navigator)?e.plugins:null)&&e.length)for(q=0;q<e.length&&!y;q++)h=e[q],-1<h.name.indexOf("Shockwave Flash")&&(y=h.description);if(!y)try{var oa=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7");y=oa.GetVariable("$version")}catch(Nd){}if(!y)try{oa=
new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),y="WIN 6,0,21,0",oa.AllowScriptAccess="always",y=oa.GetVariable("$version")}catch(Nd){}if(!y)try{oa=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),y=oa.GetVariable("$version")}catch(Nd){}y&&(oa=y.match(/[\d]+/g))&&3<=oa.length&&(y=oa[0]+"."+oa[1]+" r"+oa[2]);c.call(a,pb,y||void 0);a.set(kb,p.characterSet||p.charset);a.set(ob,b&&"function"===typeof b.javaEnabled&&b.javaEnabled()||!1);a.set(jb,(b&&(b.language||b.browserLanguage)||"").toLowerCase());
a.data.set(Dd,sd("gclid",!0));a.data.set(Gd,sd("gclsrc",!0));a.data.set(Ed,Math.round((new Date).getTime()/1E3));a.get(Dd)||(a.data.set(se,sd("wbraid",!0)),a.data.set(te,Math.round((new Date).getTime()/1E3)));if(d&&a.get(ic)&&(b=p.location.hash)){b=b.split(/[?&#]+/);d=[];for(y=0;y<b.length;++y)(n(b[y],"utm_id")||n(b[y],"utm_campaign")||n(b[y],"utm_source")||n(b[y],"utm_medium")||n(b[y],"utm_term")||n(b[y],"utm_content")||n(b[y],"gclid")||n(b[y],"dclid")||n(b[y],"gclsrc")||n(b[y],"wbraid"))&&d.push(b[y]);
0<d.length&&(b="#"+d.join("&"),a.set(gb,a.get(gb)+b))}},$c={pageview:[ib],event:[qb,rb,sb,vb],social:[wb,xb,yb],timing:[Hb,Ib,Kb,Jb]};var Tc=function(a){if("prerender"==p.visibilityState)return!1;a();return!0},fd=function(a){if(!Tc(a)){k(16);var b=!1,c=function(){if(!b&&Tc(a)){b=!0;var d=c,e=p;e.removeEventListener?e.removeEventListener("visibilitychange",d,!1):e.detachEvent&&e.detachEvent("onvisibilitychange",d)}};v(p,"visibilitychange",c)}};var md=/^(?:(\w+)\.)?(?:(\w+):)?(\w+)$/,Wc=function(a){if(l(a[0]))this.L=a[0];else{var b=md.exec(a[0]);null!=b&&4==b.length&&(this.g=b[1]||"t0",this.u=b[2]||"",this.methodName=b[3],this.U=[].slice.call(a,1),this.u||(this.X="create"==this.methodName,this.s="require"==this.methodName,this.F="provide"==this.methodName,this.Y="remove"==this.methodName),this.s&&(3<=this.U.length?(this.N=this.U[1],this.M=this.U[2]):this.U[1]&&(m(this.U[1])?this.N=this.U[1]:this.M=this.U[1])));b=a[1];a=a[2];if(!this.methodName)throw"abort";
if(this.s&&(!m(b)||""==b))throw"abort";if(this.F&&(!m(b)||""==b||!l(a)))throw"abort";if(Vc(this.g)||Vc(this.u))throw"abort";if(this.F&&"t0"!=this.g)throw"abort";}};function Vc(a){return 0<=a.indexOf(".")||0<=a.indexOf(":")};var W,Xc,Yc,X;W=new x;Yc=new x;X=new x;Xc={ec:45,ecommerce:46,linkid:47};
var cd=function(a,b,c){b==Z||b.get(N);var d=W.get(a);if(!l(d))return!1;b.plugins_=b.plugins_||new x;if(b.plugins_.get(a))return!0;b.plugins_.set(a,new d(b,c||{}));return!0},ed=function(a,b,c,d,e){if(!l(W.get(b))&&!Yc.get(b)){Xc.hasOwnProperty(b)&&k(Xc[b]);var g=void 0;if(oc.test(b)){k(52);a=Z.C(a);if(!a)return!0;c=Fc(a.model,b,d,e);g=function(){Y.o(["provide",b,function(){}]);var q=z[d&&d.dataLayer||"dataLayer"];q&&q.hide&&l(q.hide.end)&&q.hide[b]&&(q.hide.end(),q.hide.end=void 0)}}!c&&Xc.hasOwnProperty(b)?
(k(39),c=b+".js"):k(43);if(c){var h;d&&(h=d[Pc]);m(h)||(h=void 0);a=Zc(ve(c,h));!h||fe(a.protocol)&&gd(a)||(a=Zc(ve(c)));fe(a.protocol)&&gd(a)&&(pc(a.url,void 0,e,void 0,g),Yc.set(b,!0))}}},dd=function(a,b){var c=X.get(a)||[];c.push(b);X.set(a,c)},hd=function(a,b){W.set(a,b);b=X.get(a)||[];for(var c=0;c<b.length;c++)b[c]();X.set(a,[])},gd=function(a){var b=Zc(p.location.href);if(n(a.url,Wd(1))||n(a.url,Wd(2)))return!0;if(a.query||0<=a.url.indexOf("?")||0<=a.path.indexOf("://"))return!1;if(a.host==
b.host&&a.port==b.port||Be&&(b=p.createElement("a"),b.href=Be,b=Ce(b),a.host===b[0]&&a.port===b[1]))return!0;b="http:"==a.protocol?80:443;return"www.google-analytics.com"==a.host&&(a.port||b)==b&&n(a.path,"/plugins/")?!0:!1},fe=function(a){var b=p.location.protocol;return"https:"==a||a==b?!0:"http:"!=a?!1:"http:"==b},Ce=function(a){var b=a.hostname||"",c=0<=b.indexOf("]");b=b.split(c?"]":":")[0].toLowerCase();c&&(b+="]");c=(a.protocol||"").toLowerCase();c=1*a.port||("http:"==c?80:"https:"==c?443:
"");a=a.pathname||"";n(a,"/")||(a="/"+a);return[b,""+c,a]},Zc=function(a){var b=p.createElement("a");b.href=p.location.href;var c=(b.protocol||"").toLowerCase(),d=Ce(b),e=b.search||"",g=c+"//"+d[0]+(d[1]?":"+d[1]:"");n(a,"//")?a=c+a:n(a,"/")?a=g+a:!a||n(a,"?")?a=g+d[2]+(a||e):0>a.split("/")[0].indexOf(":")&&(a=g+d[2].substring(0,d[2].lastIndexOf("/"))+"/"+a);b.href=a;c=Ce(b);return{protocol:(b.protocol||"").toLowerCase(),host:c[0],port:c[1],path:c[2],query:b.search||"",url:a||""}},ve=function(a,b){return a&&
0<=a.indexOf("/")?a:(b||Oc(!1))+"/plugins/ua/"+a};var Y={W:function(){Y.h=[]}};Y.W();Y.o=function(a){var b=Y.aa.apply(Y,arguments);b=Y.h.concat(b);for(Y.h=[];0<b.length&&!Y.T(b[0])&&!(b.shift(),0<Y.h.length););Y.h=Y.h.concat(b)};Y.ta=function(a){Z.q&&(300===Z.q.length&&(Z.q.shift(),Z.qd++),Z.q.push(a))};Y.aa=function(a){for(var b=[],c=0;c<arguments.length;c++)try{var d=new Wc(arguments[c]);d.F?hd(d.U[0],d.U[1]):(d.s&&(d.ea=ed(d.g,d.U[0],d.N,d.M)),b.push(d));Y.ta(arguments[c])}catch(e){}return b};
Y.T=function(a){try{if(a.L)a.L.call(z,Z.C("t0"));else{var b=a.g==bb?Z:Z.C(a.g);if(a.X){if("t0"==a.g&&(b=Z.create.apply(Z,a.U),null===b))return!0}else if(a.Y)Z.remove(a.g);else if(b)if(a.s){if(a.ea&&(a.ea=ed(a.g,a.U[0],a.N,a.M)),!cd(a.U[0],b,a.M))return!0}else if(a.u){var c=a.methodName,d=a.U,e=b.plugins_.get(a.u);e[c].apply(e,d)}else b[a.methodName].apply(b,a.U)}}catch(g){}};var Z=function(a){k(1);Y.o.apply(Y,[arguments])};Z.j={};Z.i=[];Z.ca=0;Z.na=0;Z.answer=42;var pd=[H,O,N];Z.create=function(a){var b=ia(pd,[].slice.call(arguments));b[N]||(b[N]="t0");var c=""+b[N];if(Z.j[c])return Z.j[c];b=new V(b);Z.j[c]=b;Z.i.push(b);c=w().tracker_created;if(l(c))try{c(b)}catch(d){}return b};Z.remove=function(a){for(var b=0;b<Z.i.length;b++)if(Z.i[b].get(N)==a){Z.i.splice(b,1);Z.j[a]=null;break}};Z.C=function(a){return Z.j[a]};Z.getAll=function(){return Z.i.slice(0)};
Z.V=function(){"ga"!=bb&&k(49);var a=z[bb];if(!a||42!=a.answer){Z.ca=a&&a.l;Z.na=1*new Date;Z.loaded=!0;var b=a&&a.q,c=ca(b);a=[];c?a=b.slice(0):k(50);Z.q=c?b:[];Z.q.splice(0);Z.qd=0;b=z[bb]=Z;R("create",b,b.create);R("remove",b,b.remove);R("getByName",b,b.C,5);R("getAll",b,b.getAll,6);b=V.prototype;R("get",b,b.get,7);R("set",b,b.set,4);R("send",b,b.send);R("requireSync",b,b.ja);b=Ua.prototype;R("get",b,b.get);R("set",b,b.set);if("https:"!=p.location.protocol&&!A){a:{b=p.getElementsByTagName("script");
for(c=0;c<b.length&&100>c;c++){var d=b[c].src;if(d&&0==d.indexOf(Oc(!0)+"/analytics")){b=!0;break a}}b=!1}b&&(A=!0)}(z.gaplugins=z.gaplugins||{}).Linker=U;b=U.prototype;hd("linker",U);R("decorate",b,b.S,20);R("autoLink",b,b.R,25);R("passthrough",b,b.H,25);hd("displayfeatures",Lc);hd("adfeatures",Lc);Y.o.apply(Z,a)}};var ze=Z.V,Ae=z[bb];Ae&&Ae.r?ze():fd(ze);fd(function(){Y.o(["provide","render",t])});})(window);
